config/routes.rb
Rails.application.routes.draw do
  resources :atendimentos
  resources :animals
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/home" => "home#inicio"
  
  get "/about" => "about#sobre"
  
  #get "/" => "home#inicio"
  
  get "/ideas" => "ideas#show" 
  
  root to: 'home#inicio'


devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
    get "/", :to => "users/sessions#create"
  end

  authenticated :user do
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "users/sessions#new"
    end
  end
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :animal
end

app/controllers/atendimentos_controller.rb
class AtendimentosController < ApplicationController
  before_action :set_atendimento, only: [:show, :edit, :update, :destroy]

  # GET /atendimentos
  # GET /atendimentos.json
  def index
    @atendimentos = Atendimento.all.page(params[:page]).per(4)
  end

  # GET /atendimentos/1
  # GET /atendimentos/1.json
  def show
  end

  # GET /atendimentos/new
  def new
    @atendimento = Atendimento.new
  end

  # GET /atendimentos/1/edit
  def edit
  end

  # POST /atendimentos
  # POST /atendimentos.json
  def create
    @atendimento = Atendimento.new(atendimento_params)

    respond_to do |format|
      if @atendimento.save
        format.html { redirect_to @atendimento, notice: 'Atendimento Criado.' }
        format.json { render :show, status: :created, location: @atendimento }
      else
        format.html { render :new }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atendimentos/1
  # PATCH/PUT /atendimentos/1.json
  def update
    respond_to do |format|
      if @atendimento.update(atendimento_params)
        format.html { redirect_to @atendimento, notice: 'Atendimento Atualizado.' }
        format.json { render :show, status: :ok, location: @atendimento }
      else
        format.html { render :edit }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atendimentos/1
  # DELETE /atendimentos/1.json
  def destroy
    @atendimento.destroy
    respond_to do |format|
      
      format.html { redirect_to atendimentos_url, notice: 'Atendimento Excluido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atendimento
      @atendimento = Atendimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atendimento_params
      params.require(:atendimento).permit(:animal_id, :observacao, :data)
    end
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/views/atendimentos/_form.html.erb
<%= form_with(model: atendimento, local: true) do |form| %>
  <% if atendimento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atendimento.errors.count, "error") %> prohibited this atendimento from being saved:</h2>

      <ul>
      <% atendimento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :animal_id %>
    <%= form.select("animal_id", Animal.all.collect {|a| [ a.nome, a.id ] }, {include_blank:'Selecione...'}, :class => 'myclass')%>   
  </div>

  <div class="field">
    <%= form.label :observacao %>
    <%= form.text_field :observacao %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_field :data %>
  </div>

  <div class="actions">
    <%= form.submit(:class => 'button') %>
  </div>
<% end %>

app/views/atendimentos/edit.html.erb
<%= render 'layouts/navigation' %>
<div id="novo">
    <h1>Editar Atendimento</h1>
    
    <%= render 'form', atendimento: @atendimento %>
    
    <%= link_to 'Show', @atendimento, class:"btn btn-1 btn-1a" %>
    <%= link_to 'Back', atendimentos_path, class:"btn btn-1 btn-1a" %>
</div>

app/views/atendimentos/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<%= render 'layouts/navigation' %>
<div class="main">
  <div id="alinha-content">
    <h1>Atendimentos</h1>
  
  <table>
    <thead>
      <tr>
        <th>Animal</th>
        <th>Observação</th>
        <th>Data</th>
        <th>Ações</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @atendimentos.each do |atendimento| %>
        <tr>
        
          <td><%= atendimento.animal.nome %></td>
          <td><%= atendimento.observacao %></td>
          <td><%= atendimento.data %></td>
          <!--strftime("%d/%m/%Y")-->
          <td><%= link_to atendimento do%>
             <i class="fas fa-eye"></i>
             <%end%>
          </td>
          
          <td><%= link_to edit_atendimento_path(atendimento) do %>
            <i class="fas fa-edit">
              </i>
            <% end %>
          </td>
          
          <td><%= link_to atendimento, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' } do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Novo Atendimento', new_atendimento_path, class:"myButton" %>
  
     <div class="paginacao">
        <%= paginate @atendimentos, class: "pagination" %>
      </div>
  </div>
</div>

app/views/atendimentos/new.html.erb
<%= render 'layouts/navigation' %>
<div id="novo">
    <h1>Novo Atendimento</h1>

    <%= render 'form', atendimento: @atendimento %>

    <%= link_to 'Voltar', atendimentos_path,class:"btn btn-1 btn-1a"  %>
</div>

app/views/atendimentos/show.html.erb
<%= render 'layouts/navigation' %>


<div class="container-show">
  <div id="mostrar">
     <h1>Atendimento do Animal</h1>
    <p id="notice"><%= notice %></p>
    
    <div class="inf">
      <%= link_to image_tag("perfil-atendimento.png", :alt => "logo", class:"cliente-photo") %> 
    
      <div class="alinha-show">
        <p>
          <strong>Animal:</strong>
          <%= @atendimento.animal.nome %>
        </p>
      </div>
      
      <div class="alinha-show">
        <p>
          <strong>Observação:</strong>
          <%= @atendimento.observacao %>
        </p>
      </div>
      
      <div class="alinha-show">
        <p>
          <strong>Data:</strong>
          <%= @atendimento.data %>
        </p>
      </div>
      
        <%= link_to 'Editar', edit_atendimento_path(@atendimento), class: "btn btn-1 btn-1a" %>
        <%= link_to 'Voltar', atendimentos_path, class: "btn btn-1 btn-1a" %>
       </div>
    </div>
</div>