config/routes.rb
Rails.application.routes.draw do
  resources :atendimentos
  resources :animals
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/home" => "home#inicio"
  
  get "/about" => "about#sobre"
  
  #get "/" => "home#inicio"
  
  get "/ideas" => "ideas#show" 
  
  root to: 'home#inicio'


devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
    get "/", :to => "users/sessions#create"
  end

  authenticated :user do
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "users/sessions#new"
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :cliente
  has_many :atendimento, dependent: :destroy
  
  validates_presence_of :nome, message: 'não pode ser deixado em branco'
  validates_presence_of :especie, message: 'não pode ser deixado em branco'
  validates_presence_of :raca, message: 'não pode ser deixado em branco'

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.order("nome").page(params[:page]).per(4)
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal Criado.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal Atualizado.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal Excluido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nome, :cliente_id, :especie, :raca, :nascimento)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cliente_id %>
    <%= form.select("cliente_id", Cliente.all.collect {|m| [ m.nome, m.id ] }, {include_blank:'Selecione...'}, :class => 'myclass')%>   
  </div>

  <div class="field">
    <%= form.label :especie %>
    <%= form.text_field :especie %>
  </div>

  <div class="field">
    <%= form.label :raca %>
    <%= form.text_field :raca %>
  </div>

  <div class="field">
    <%= form.label :nascimento %>
    <%= form.date_field :nascimento %>
  </div>

  <div class="actions">
    <%= form.submit(:class => 'button') %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<%= render 'layouts/navigation' %>
<style>
    .btn_back{
        color: purple;
        
    }
</style>

<div id="novo">
    <h1>Editar Animal</h1>
    
    <%= render 'form', animal: @animal %>
    
    <%= link_to 'Show', @animal, class:"btn btn-1 btn-1a" %> 
    <%= link_to 'Back', animals_path, class:"btn btn-1 btn-1a" %>
</div>

app/views/animals/index.html.erb
<%= stylesheet_link_tag "clientes" %>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<%= render 'layouts/navigation' %>
<div class= "main">
  <div id="alinha-content">
    <h1>Animais</h1>
    
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Cliente</th>
          <th>Espécie</th>
          <th>Raça</th>
          <th>Data de Nascimento</th>
          <th>Ações</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        
        <% @animals.each do |animal| %>
           
          
          <tr data-link = '<%= link_to 'Mostrar', animal %>'>
           <td><%= animal.nome %></td>
            <td><%= animal.cliente.nome %></td>
            <td><%= animal.especie %></td>
            <td><%= animal.raca %></td>
            <td><%= animal.nascimento.strftime("%d/%m/%Y") %></td>
            <td><%= link_to animal do %>
              <i class="fas fa-eye"></i>
               <%end%>
            </td>
            <td><%= link_to edit_animal_path(animal) do %>
                <i class="fas fa-edit"></i>
              <% end %>
            </td>
            <td><%= link_to animal, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' } do%>
               <i class="fas fa-trash-alt"></i>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    

    <br>
    
    
    <%= link_to 'Adicionar Animal', new_animal_path, class: "myButton" %>
    
      <div class="paginacao">
        <%= paginate @animals, class: "pagination" %>
      </div>
      
    </div>
</div>

app/views/animals/new.html.erb
<%= render 'layouts/navigation' %>
<div id="novo">
    <h1>Novo Animal</h1>

    <%= render 'form', animal: @animal %>

    <%= link_to 'Voltar', animals_path, class:"btn btn-1 btn-1a"  %>
</div>

app/views/animals/show.html.erb
<%= render 'layouts/navigation' %>

<div class="container-show">
  <div id="mostrar">
    <h1>Informações do Animal</h1>
    
    <div class="inf">
        <%= link_to image_tag("perfil-animal.png", :alt => "logo", class:"cliente-photo") %> 
      <div class="alinha-show">
        <p>
          <strong>Nome:</strong>
          <%= @animal.nome %>
        </p>
      </div>
      
      <div class="alinha-show">
        <p>
          <strong>Cliente:</strong>
          <%= @animal.cliente.nome %>
        </p>
      </div>
      
      <div class="alinha-show">
        <p>
          <strong>Espécie:</strong>
          <%= @animal.especie %>
        </p>
      </div>
      
      <div class="alinha-show">
        <p>
          <strong>Raça:</strong>
          <%= @animal.raca %>
        </p>
      </div>
      
      <div class="alinha-show">
        <p>
          <strong>Nascimento:</strong>
          <%= @animal.nascimento %>
        </p>
      </div>
      
      <%= link_to 'Editar', edit_animal_path(@animal), class: "btn btn-1 btn-1a" %>
      <%= link_to 'Voltar', animals_path, class: "btn btn-1 btn-1a" %>
    </div>
  </div>
</div>