config/routes.rb
Rails.application.routes.draw do
  resources :atendimentos
  resources :animals
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/home" => "home#inicio"
  
  get "/about" => "about#sobre"
  
  #get "/" => "home#inicio"
  
  get "/ideas" => "ideas#show" 
  
  root to: 'home#inicio'


devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
    get "/", :to => "users/sessions#create"
  end

  authenticated :user do
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "users/sessions#new"
    end
  end
end

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>

<%= stylesheet_link_tag "clientes" %>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <div id="container">
        <ul class="nav"
        
          <li class="active"><a href="/ideas">Ideas</a></li>
        </ul>
  
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
        
          <div id= "login_user" style="position: relative; top: 5px; left: -10%" >Logado como: <strong><%= current_user.username %></strong>.
          
          <div style="position: relative; float: right; top: -10px;">
            <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link', class:"btn btn-1 btn-1a" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', class:"btn btn-1 btn-1a" %></div>
          </div>
          
          <% else %>
      
          <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    
  </div>
  
  <div class="sidenav">
    <%= link_to image_tag("logo.png", :alt => "Logo do vet system", class:"logo"), (home_path), class:"aLogo" %>
    
    <div>
      <%= link_to 'Home', home_path, class:"menu"%>
      <%= link_to 'Clientes', clientes_path, class:"menu" %>
      <%= link_to 'Animais', animals_path, class:"menu" %>
      <%= link_to 'Atendimentos', atendimentos_path, class:"menu" %>
      <%= link_to 'Sobre', about_path, class:"menu" %>
    </div>
    
  </div>

<div class="main">
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vetsystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= yield %>
  </body>
</html>